### ISSUE TITLE
How Can  I  used these code?

### ISSUE THREAD

**Issue by wangruihuan** [V-Sense/LFToolbox-CLIM_VSENSE#1]
If there is a demo code that show how to use the proposed method to decode LF from Raw data.

**Comment by malain35** [comment]
Hi, you can follow the same steps as in the original LFToolbox by Donald Dansereau, as explained in LFToolbox.pdf, making sure you use the LFToolbox-CLIM_VSENSE folder in your path.
Best,
Martin

**Comment by wangruihuan** [comment]
Thanks for your reply. I followed the instructions on the github you mentioned to modify，&nbsp;
as shown below.
&nbsp;&nbsp;

&nbsp; &nbsp;However,&nbsp; the result is the same as the original LFToolbox by Donald Dansereau generated and I add them in attachment. I guess if there are any other details that I have overlooked.&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Martin"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月9日(星期一) 晚上8:54
收件人:&nbsp;"V-Sense/LFToolbox-CLIM_VSENSE"<LFToolbox-CLIM_VSENSE@noreply.github.com&gt;;
抄送:&nbsp;"rhwang"<2930058648@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [V-Sense/LFToolbox-CLIM_VSENSE] How Can  I  used these code? (#1)




Hi, you can follow the same steps as in the original LFToolbox by Donald Dansereau, as explained in LFToolbox.pdf, making sure you use the LFToolbox-CLIM_VSENSE folder in your path.
 Best,
 Martin

**Comment by malain35** [comment]
Hi, sorry we can not see attachment.
Results should be different when using this version of the toolbox, if you have the same results as the original toolbox it could indicate that the original toolbox folder is still present in your Matlab path. In addition to adding this toolbox to the path, make sure the original one is removed. In addition you can check that the additional decoding options described in the Readme file are set to default values. Hope this help.
Best,
Martin
